---
title: "Bitacora 1"
author: 
  - Sebastián Rojas Vargas
  - Francisco Soto Quesada
  - Jairo Pacheco Campos
  - Jason Barrantes Rodríguez
date: "11/4/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Inicio:** 2:00 pm 

**Cierre:** 3:20 pm

# Acuerdos

-	Se escogió la base datos de diamantes, paquete ggplot2.
-	Son 8 IC a calcular, repartirlos en dos para cada uno.
-	Creación de un repositorio en github para almacenar el proyecto de R y llevar un mejor control del mismo.
-	Se escogieron las variables: precio, corte, profundidad y quilates.

# Distribución de tareas:


| Tareas| Responsable|
|:--|:--|
|Promedio usando distribución z | Sebastian Rojas Vargas|
|Promedio usando distribución t	| Sebastian Rojas Vargas|
|Proporción	| Jason Barrantes Rodriguez|
|Varianza	| Jairo Pacheco Campos|
|Diferencia de promedios usando distribución z | Francisco Soto Quesada|
|Diferencia de promedios usando distribución t | Francisco Soto Quesada|
|Diferencia de proporciones	| Jason Barrantes Rodriguez|
|Cociente de varianzas | Jairo Pacheco Campos|


